/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online_examination_system;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Dell
 */
public class StudentForm extends javax.swing.JFrame {

    /**
     * Creates new form StudentForm
     */
    //Timer 
    private Timer time;
        //Database Connection
   private static final String username ="root"; 
   private static final String password ="Campmake96"; 
   private static final String dataconnect ="jdbc:mysql://localhost:3306/online_testing_system"; 
   
    Connection connect = null;
    PreparedStatement pst =null;
    ResultSet rs = null;
    int q ,i;
    public StudentForm() {
        initComponents();
        
        time =new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            Countdown();
            }
        });
        
        time.start();
    }
    int x =60;
    public void Countdown()
    {
    x--;
    nako.setText(String.valueOf(x));
    if(x ==0)
    {
   JOptionPane.showMessageDialog(null, "Time up!!!!!!!!");
    System.exit(0);
    
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     public void updateDB() 
    {
    try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
        connect =DriverManager.getConnection(dataconnect ,username ,password);
        pst =connect.prepareStatement("Select * from teache_table");
        rs = pst.executeQuery();
        java.sql.ResultSetMetaData stdata = rs.getMetaData();
         q = stdata.getColumnCount();
         
         
         
        while(rs.next())
        {
        Vector columbaData = new Vector();
        
        for(i =1;i <=q ;i++)
        {
        columbaData.add(rs.getString("idTeache_Table"));
        columbaData.add(rs.getString("Teacher_Name"));
        columbaData.add(rs.getString("Question1"));
        columbaData.add(rs.getString("Question2"));
        columbaData.add(rs.getString("Question3"));
        columbaData.add(rs.getString("Question4"));
        columbaData.add(rs.getString("Question5"));
        
        }

        }
        
        
    }  catch (Exception ex) {
           JOptionPane.showMessageDialog(null, "error");
       }
    
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TestSubmit = new javax.swing.JButton();
        Q4Combo = new javax.swing.JComboBox<>();
        Q3Combo = new javax.swing.JComboBox<>();
        Q2Combo = new javax.swing.JComboBox<>();
        Question5Combo = new javax.swing.JComboBox<>();
        Q1Combo = new javax.swing.JComboBox<>();
        NameTest = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nako = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Test");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Total : 10");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Question 1 :Who was the last apartheid president?");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Question 2:Who was the second black president?");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Question 3:What prison was Nelson Mandela held up?");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Question 4 : Who was Nelson Mandela wife?");
        jLabel7.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Question 5:What year was apartheid come to an end?");

        TestSubmit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TestSubmit.setText("Submit");
        TestSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestSubmitActionPerformed(evt);
            }
        });

        Q4Combo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Q4Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Selina Willaim", "Khumo Motimele", "None" }));

        Q3Combo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Q3Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Robin Island", "Kgosi Mampuru Prison", "GT4 Prison" }));
        Q3Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q3ComboActionPerformed(evt);
            }
        });

        Q2Combo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Q2Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Nelson Mandela", "Thabo Mbheki", "Jacob Zuma" }));

        Question5Combo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Question5Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1994", "2010", "2020" }));

        Q1Combo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Q1Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Nelson Mandela", "FW De Klerk", "Cyril Ramaphosa" }));

        NameTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTestActionPerformed(evt);
            }
        });

        jLabel9.setText("Timer:");

        nako.setText("60");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(TestSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(217, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(Question5Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Q3Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(Q4Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addComponent(Q2Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Q1Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NameTest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(nako)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nako))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NameTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q1Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q2Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(Q3Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Q4Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Question5Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TestSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Q3ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q3ComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q3ComboActionPerformed

    private void NameTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTestActionPerformed

    private void TestSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestSubmitActionPerformed
        // Submitting Answers
        
         try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
        connect =DriverManager.getConnection(dataconnect ,username ,password);
        pst =connect.prepareStatement("insert into  online_testing_system.teache_table( Teacher_Name, Question1, Question2, Question3, Question4, Question5) value(?,?,?,?,? ,?)");
        
        pst.setString(1, NameTest.getText());
        pst.setString(2, Q1Combo.getSelectedItem().toString());
        pst.setString(3, Q2Combo.getSelectedItem().toString());
        pst.setString(4, Q3Combo.getSelectedItem().toString());
        pst.setString(5, Q4Combo.getSelectedItem().toString());
        pst.setString(6, Question5Combo.getSelectedItem().toString());  
        pst.executeUpdate();
        
        
        //Creating Grading
        String Q1 =Q1Combo.getSelectedItem().toString();
        int Q1result;
        if(Q1 =="FW De Klerk")
        { Q1result =2;
        }else { Q1result =0;}
        
        
        String Q2 =Q2Combo.getSelectedItem().toString();
        int Q2result;
        if(Q2 =="Thabo Mbheki")
        { Q2result =2;
        }else { Q2result =0;}
        
        String Q3 =Q3Combo.getSelectedItem().toString();
        int Q3result;
        if(Q3 =="Robin Island")
        { Q3result =2;
        }else { Q3result =0;}
        
        String Q4 =Q4Combo.getSelectedItem().toString();
        int Q4result;
        if(Q4 =="None")
        { Q4result =2;
        }else { Q4result =0;}
        
        String Q5 =Question5Combo.getSelectedItem().toString();
        int Q5result;
        if(Q5 =="1994")
        { Q5result =2;
        }else { Q5result =0;}



        int totalResults =Q1result +Q2result +Q3result +Q4result +Q5result;
        if(totalResults ==2)
        {
       JOptionPane.showMessageDialog(null, NameTest + " ,you have successfully saved your Answered and you have scored: " +totalResults +"  points which is 20% try harder");

        }else if(totalResults ==4)
        {
       JOptionPane.showMessageDialog(null, NameTest + " ,you have successfully saved your Answered and you have scored: " +totalResults +"  points which is 40% Almost there");

        }else if(totalResults ==6)
        {
       JOptionPane.showMessageDialog(null, NameTest + " ,you have successfully saved your Answered and you have scored: " +totalResults +"  points which is 60% Welldone");

        }else if(totalResults ==8)
        {
       JOptionPane.showMessageDialog(null, NameTest + " ,you have successfully saved your Answered and you have scored: " +totalResults +"  points which is 80% Disntiction");

        }else if(totalResults ==10)
        {
       JOptionPane.showMessageDialog(null, NameTest + " ,you have successfully saved your Answered and you have scored: " +totalResults +"  points which is 100% Excellent");

        }
        
        
        
        
        
        
        
        
        
        
        //Messages
        
        updateDB();
         StudentForm sf = new StudentForm();
        sf.setVisible(true);
    }catch(Exception ex)
    {
    JOptionPane.showMessageDialog(null, ex);
    }
       
    }//GEN-LAST:event_TestSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentForm().setVisible(true);
            }
      });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NameTest;
    private javax.swing.JComboBox<String> Q1Combo;
    private javax.swing.JComboBox<String> Q2Combo;
    private javax.swing.JComboBox<String> Q3Combo;
    private javax.swing.JComboBox<String> Q4Combo;
    private javax.swing.JComboBox<String> Question5Combo;
    private javax.swing.JButton TestSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel nako;
    // End of variables declaration//GEN-END:variables
}
